modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/GlobalXP/blob/1.19/LICENSE"

[[mods]]
	modId="globalxp"
	version="${file.jarVersion}"
	displayName="Global XP"
	description='''Adds a fast way to store XP and share it with your friends!'''
	issueTrackerURL="https://github.com/bl4ckscor3/GlobalXP/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/global-xp"
	authors="bl4ckscor3"

[[dependencies.globalxp]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.globalxp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"